
/**************************************************************
 *	
 *	collectSound, 8 bit, 11025Hz,
 *	1 channel, 12384 bytes/channel
 *	Total Size: 1 * 12384 + 4 (header) = 12428 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\collectSound.wav
 *	Time-stamp: Fri Apr 17 20:17:21 2020
 *	
 **************************************************************/

#ifndef __COLLECTSOUNDH__
#define __COLLECTSOUNDH__

#define COLLECTSOUNDFREQ 11025
#define COLLECTSOUNDLEN 12384

extern const unsigned char collectSound[12384];

#endif /* __COLLECTSOUNDH__ */
