
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 1100494 bytes/channel
 *	Total Size: 1 * 1100494 + 4 (header) = 1100538 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\gameSong.wav
 *	Time-stamp: Fri Apr 17 20:18:13 2020
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1100494

extern const unsigned char gameSong[1100494];

#endif /* __GAMESONGH__ */
