
/**************************************************************
 *	
 *	loseSong, 8 bit, 11025Hz,
 *	1 channel, 374131 bytes/channel
 *	Total Size: 1 * 374131 + 4 (header) = 374175 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\loseSong.wav
 *	Time-stamp: Fri Apr 17 20:19:42 2020
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 374131

extern const unsigned char loseSong[374131];

#endif /* __LOSESONGH__ */
