
/**************************************************************
 *	
 *	menuSong, 8 bit, 11025Hz,
 *	1 channel, 317934 bytes/channel
 *	Total Size: 1 * 317934 + 4 (header) = 317978 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\menuSong.wav
 *	Time-stamp: Fri Apr 17 20:53:16 2020
 *	
 **************************************************************/

#ifndef __MENUSONGH__
#define __MENUSONGH__

#define MENUSONGFREQ 11025
#define MENUSONGLEN 317934

extern const unsigned char menuSong[317934];

#endif /* __MENUSONGH__ */
