
/**************************************************************
 *	
 *	owSound, 8 bit, 11025Hz,
 *	1 channel, 3516 bytes/channel
 *	Total Size: 1 * 3516 + 4 (header) = 3560 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\owSound.wav
 *	Time-stamp: Fri Apr 17 22:39:33 2020
 *	
 **************************************************************/

#ifndef __OWSOUNDH__
#define __OWSOUNDH__

#define OWSOUNDFREQ 11025
#define OWSOUNDLEN 3516

extern const unsigned char owSound[3516];

#endif /* __OWSOUNDH__ */
