
/**************************************************************
 *	
 *	pauseSound, 8 bit, 11025Hz,
 *	1 channel, 84562 bytes/channel
 *	Total Size: 1 * 84562 + 4 (header) = 84606 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\pauseSound.wav
 *	Time-stamp: Fri Apr 17 20:21:21 2020
 *	
 **************************************************************/

#ifndef __PAUSENOISEH__
#define __PAUSENOISEH__

#define PAUSENOISEFREQ 11025
#define PAUSENOISELEN 84562

extern const unsigned char pauseNoise[84562];

#endif /* __PAUSESOUNDH__ */
