
/**************************************************************
 *	
 *	punchSound, 8 bit, 11025Hz,
 *	1 channel, 4206 bytes/channel
 *	Total Size: 1 * 4206 + 4 (header) = 4250 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\punchSound.wav
 *	Time-stamp: Fri Apr 17 20:22:01 2020
 *	
 **************************************************************/

#ifndef __PUNCHSOUNDH__
#define __PUNCHSOUNDH__

#define PUNCHSOUNDFREQ 11025
#define PUNCHSOUNDLEN 4206

extern const unsigned char punchSound[4206];

#endif /* __PUNCHSOUNDH__ */
