
/**************************************************************
 *	
 *	sanSound, 8 bit, 11025Hz,
 *	1 channel, 13967 bytes/channel
 *	Total Size: 1 * 13967 + 4 (header) = 14011 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\sanSound.wav
 *	Time-stamp: Sun Apr 19 18:53:01 2020
 *	
 **************************************************************/

#ifndef __SANSOUNDH__
#define __SANSOUNDH__

#define SANSOUNDFREQ 11025
#define SANSOUNDLEN 13967

extern const unsigned char sanSound[13967];

#endif /* __SANSOUNDH__ */
