
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 318006 bytes/channel
 *	Total Size: 1 * 318006 + 4 (header) = 318050 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\tamji\OneDrive\Desktop\CS 2261\M04\final-project-thossain30\winSong.wav
 *	Time-stamp: Fri Apr 17 20:22:33 2020
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 318006

extern const unsigned char winSong[318006];

#endif /* __WINSONGH__ */
